apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: nagp-app
  labels:
    app: postgres
spec:
  storageClassName: standard-rwo-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
