apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: nagp-app
  labels:
    app: postgres
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: YWRtaW5wYXNzb3dyZA==
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW5wYXNzb3dyZA==
  POSTGRES_DB: ZW1wbG95ZWVkYg==
